import Sunburst from 'sunburst-chart'
import * as d3 from 'd3'

export function SunburstObject(data, customs) {
    const myChart = Sunburst();

    //Chart data and size instantiation
    myChart
        .data(data)
        .size('size');

    //Check if color values were given. If not, color values are autogenerated for each node.
    if (typeof data.color != "undefined") {
        myChart.color('color');
    } else {
        //Each ring has its own color
        const color = d3.scaleOrdinal(d3.schemePaired);
        myChart.color((d, parent) => color(parent ? parent.data.name : null));
    }

    //Widget parameters given from the php widget class
    let customTooltipCheck = false;
    if ((customs != null)) {
        if ((Object.keys(customs).length != 0)) {
            for (const [key, value] of Object.entries(customs)) {
                myChart[key](value)

                //If custom tooltip parameter given, default customization gets disabled.
                if ((key === "tooltipTitle") || (key === "tooltipContent")) {
                    customTooltipCheck = true;
                }
            };
        }
    }

    //Default tooltip customization
    if (!customTooltipCheck) {
        defaultTooltipCustomization();
    }

    //Final instantiation:
    myChart(document.getElementById("myChart"));

    //Some extra styling:
    extraChartStyling();

    //Methods

    function toTitleCase(str) {
        if (!str) {
            return '';
        }
        const strArr = str.split(' ').map((word) => {
            return word[0].toUpperCase() + word.substring(1).toLowerCase();
        });
        return strArr.join(' ');
    }

    function defaultTooltipCustomization() {
        myChart
        .tooltipTitle(function (d, node) {

            console.log(node);
            let tooltipData = toTitleCase(node.data.name) + ": <i>"+node.data.size+'</i>';

            let currentNode = node;
            let parentName;
            let count = 0;
            do {
                if ((currentNode.parent != null)) {

                    parentName = currentNode.parent.data.name;

                    if (currentNode.parent.parent !=null) {
                        tooltipData = parentName + " > " + tooltipData;
                    }

                    currentNode = currentNode.parent;

                    console.log(currentNode);

                    if (count > 50) {
                        console.log("Error: infinite loop");
                        break;
                    }
                } else {

                    break;
                }
                count++;
            } while (true);

            return toTitleCase(tooltipData);
        });

    }

    function extraChartStyling() {
        svgElement = document.getElementsByClassName("sunburst-viz").firstChild;
        svgElement.setAttribute('viewBox', "0 0 100 100");
        svgElement.setAttribute("preserveAspectRatio", "xMidYMid meet");

        gElement = document.getElementByClassName("sunburst-viz").children[0].children[0];
        gElement.setAttribute("class", "g-chart-content");

    }
  }
